apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drf8024-hello-cuda
  labels:
    app: cuda-hello
    user: http://cilogon.org/serverE/users/495644
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
