apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drf8024-hello-cuda-pvc
  labels:
    app: drf8024-cuda-hello
    user: drf8024
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

